name: Deploy da Documentação
on:
  push:
    branches:
      - main  # Ou 'master', dependendo de como está seu repo

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o seu código para o servidor do GitHub
      - uses: actions/checkout@v4

      # 2. Instala o Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3. Configura o Cache (para ser mais rápido nas próximas vezes)
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # 4. Instala o MkDocs e o Tema Material
      - run: pip install mkdocs-material 

      # 5. Constrói o site e manda para a branch 'gh-pages'
      - run: mkdocs gh-deploy --force